### ISSUE TITLE
how to read the dataset file

### ISSUE THREAD

**Issue by caiquanyou** [gao-lab/Cell_BLAST#13]
@Jeff1995 Hi， I want to test the public dataset provided in https://cblast.gao-lab.org/download
but how to read the h5 file，I tried scanpy but  failed

**Comment by Jeff1995** [comment]
You can just use

```python
dataset = cb.data.ExprDataSet.read_dataset("filename.h5")
```

See example [here](https://cblast.gao-lab.org/doc/_static/DIRECTi.html).

**Comment by caiquanyou** [comment]
Thanks
