### ISSUE TITLE
how to build my own references

### ISSUE THREAD

**Issue by xjs1996** [gao-lab/Cell_BLAST#18]
Hi, Thank you for releasing such a good tool for annotation, and I have some questions about building a personal reference. I read your script under /Datasets/collect, and found that some data need annotation files (eg.collect_macparland.py), some other doesn't (eg. collect_chen.R, and in this script ,the input is a rds file, which is confusing because I don't know the exact structure of this data). If you don't mind, would you please just release the "download" directory or some data in this directory? Beacause they are the input of BLAST.ipynb and DIRECTi.ipynb.

**Comment by Jeff1995** [comment]
Custom data objects can be constructed via an AnnData like interface:

https://cblast.gao-lab.org/doc-latest/modules/Cell_BLAST.data.html#Cell_BLAST.data.ExprDataSet
