### ISSUE TITLE
Could we use immgen datasets as a reference?

### ISSUE THREAD

**Issue by chansigit** [gao-lab/Cell_BLAST#4]
Dear Developers?
Thank you for you CellBlast.
I recently used SingleR and found the built-in ImmGen reference  very useful. Could we use that dataset in CellBlast?

Thank you for your response.

**Comment by Jeff1995** [comment]
Thanks for your interest for Cell BLAST!

In principle Cell BLAST can be used with any scRNA-seq reference data. You may read custom reference data via functions like [read_table](https://cblast.gao-lab.org/doc/doc/Cell_BLAST.data.ExprDataSet.read_table.html), [from_anndata](https://cblast.gao-lab.org/doc/doc/Cell_BLAST.data.ExprDataSet.from_anndata.html) and [from_loom](https://cblast.gao-lab.org/doc/doc/Cell_BLAST.data.ExprDataSet.from_loom.html) in the Python package, and then train your own model on the custom reference (this [tutorial](https://cblast.gao-lab.org/doc/_static/BLAST.html) might help).

However, the ImmGen reference in SingleR (`SingleR::ImmGenData`) seems to be microarray data, which may not match the probability model used by Cell BLAST, and the data size (830 cells) is too small for the Cell BLAST model to train properly, so it's not recommended to use Cell BLAST with ImmGen. I would recommend using larger scRNA-seq datasets (> 3,000 cells) as reference in this case .
