### ISSUE TITLE
snakemake question help

### ISSUE THREAD

**Issue by caiquanyou** [gao-lab/Cell_BLAST#7]
when I Reproduce results as th page said by ran `snakemake -prk`
and iget an error like this:
Traceback (most recent call last):
  File "/root/test_cb_repro/Cell_BLAST/Evaluation/.snakemake/scripts/tmpjl7pf7be.dimension_reduction_metrics.py", line 54, in <module>
    main()
  File "/root/test_cb_repro/Cell_BLAST/Evaluation/.snakemake/scripts/tmpjl7pf7be.dimension_reduction_metrics.py", line 36, in main
    y = y[~utils.na_mask(y)]
AttributeError: module 'utils' has no attribute 'na_mask'
How to fix and rerun?

**Comment by Jeff1995** [comment]
Could you please verify that the `na_mask` function is defined in `Evaluation/utils.py`? (Should be in line 15 if you are using the latest version of the repo.)

If it is indeed defined, it is most likely caused by incorrect module being imported. Could you please insert a diagnostic line after the import section of `Evaluations/dimension_reduction_metrics.py`, like below:

```python
import argparse
import json
import Cell_BLAST as cb
import utils
print(utils.__file__)  # Add this line
```

Rerun snakemake again and check the output?

**Comment by caiquanyou** [comment]
May work ，result below：
/root/miniconda3/envs/cb-gpu/bin/python3.6 /root/test_cb_repro/Cell_BLAST/Evaluation/.snakemake/scripts/tmpeoigrv72.dimension_reduction_metrics.py
/root/test_cb_repro/Cell_BLAST/Evaluation/utils.py
[Thu Aug 27 11:27:04 2020]
Finished job 4539.
7 of 10334 steps (0.07%) done


[Thu Aug 27 11:27:05 2020]
rule dimension_reduction_metrics:
&nbsp; &nbsp; input: ../Datasets/data/Bach/data.h5, ../Results/scPhere/Bach/dim_10/seed_4/result.h5
&nbsp; &nbsp; output: ../Results/scPhere/Bach/dim_10/seed_4/metrics.json
&nbsp; &nbsp; jobid: 4530
&nbsp; &nbsp; reason: Missing output files: ../Results/scPhere/Bach/dim_10/seed_4/metrics.json
&nbsp; &nbsp; wildcards: method=scPhere, dataset=Bach, dimensionality=10, seed=4






caiqy






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gao-lab/Cell_BLAST"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午5:05
收件人:&nbsp;"gao-lab/Cell_BLAST"<Cell_BLAST@noreply.github.com&gt;;
抄送:&nbsp;"xianmao"<951463554@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gao-lab/Cell_BLAST] snakemake question help (#7)





 
Could you please verify that the na_mask function is defined in Evaluation/utils.py? (Should be in line 15 if you are using the latest version of the repo.)
 
If it is indeed defined, it is most likely caused by incorrect module being imported. Could you please insert a diagnostic line after the import section of "Evaluations/dimension_reduction_metrics.py", like below:
 import argparse import json import Cell_BLAST as cb import utils print(utils.__file__)  # Add this line
 
Rerun snakemake again and check the output?

**Comment by Jeff1995** [comment]
If "/root/test_cb_repro/Cell_BLAST/Evaluation/utils.py" is the output of the diagnostic print statement, the imported module should be correct. So is the error about `na_mask` gone?

**Comment by caiquanyou** [comment]
I rewrite the relative imports and it may works for now&nbsp;



caiqy


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gao-lab/Cell_BLAST"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 晚上7:40
收件人:&nbsp;"gao-lab/Cell_BLAST"<Cell_BLAST@noreply.github.com&gt;;
抄送:&nbsp;"xianmao"<951463554@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gao-lab/Cell_BLAST] snakemake question help (#7)





 
If "/root/test_cb_repro/Cell_BLAST/Evaluation/utils.py" is the output of the diagnostic print statement, the imported module should be correct. So is the error about na_mask gone?

**Comment by Jeff1995** [comment]
Okay great. Let me know if further issues were encountered.
