### ISSUE TITLE
snakemake CPU question

### ISSUE THREAD

**Issue by caiquanyou** [gao-lab/Cell_BLAST#8]
the snakemake runs no other problem ,but in this step run_ZIFA.py,it took 100%CPU occupied.
 timeout 12h python -u run_ZIFA.py -i ../Datasets/data/Bach/data.h5 -o ../Results/ZIFA/Bach/dim_20/seed_15/result.h5 -g seurat_genes -d 20 -s 15 --clean cell_ontology_class > ../Results/ZIFA/Bach/dim_20/seed_15/log.txt 2>&1
few hours no output,is it something wrong?

**Comment by Jeff1995** [comment]
I observed the same thing. It should be normal. ZIFA indeed seems slow on large datasets like "Bach".

**Comment by caiquanyou** [comment]
Ok,then i just keep it running and wait for output ,thx!



caiqy


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gao-lab/Cell_BLAST"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月28日(星期五) 下午4:58
收件人:&nbsp;"gao-lab/Cell_BLAST"<Cell_BLAST@noreply.github.com&gt;;
抄送:&nbsp;"xianmao"<951463554@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gao-lab/Cell_BLAST] snakemake CPU question (#8)





 
I observed the same thing. It should be normal. ZIFA indeed seems slow on large datasets like "Bach".
